kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 127.0.0.1
  kubeProxyMode: nftables
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 18880
    listenAddress: 127.0.0.1
- role: worker
  extraMounts:
  - hostPath: /Users/nick/git/lighter/.logs/kind-m5/share
    containerPath: /host-fixture
