#!/usr/bin/env bash
# Regenerate src/ort_sys.rs from ONNX Runtime's C API headers at the release
# the plugin EP is built against. That is the OLDEST ONNX Runtime that can
# load it (a runtime serves any API version up to its own), not the newest:
# raise it only when the plugin needs something a later release added.
# Needs bindgen (cargo install bindgen-cli) and libclang.
set -euo pipefail
ORT_VERSION="${ORT_VERSION:-1.23.2}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
base="https://raw.githubusercontent.com/microsoft/onnxruntime/v$ORT_VERSION/include/onnxruntime/core/session"
for h in onnxruntime_c_api.h onnxruntime_ep_c_api.h; do
	curl -fsSL "$base/$h" -o "$TMP/$h"
done
bindgen "$TMP/onnxruntime_c_api.h" --use-core --no-doc-comments --no-layout-tests \
	--allowlist-type 'Ort.*|ONNX.*' --allowlist-function 'OrtGetApiBase' --allowlist-var 'ORT_.*' \
	-o "$TMP/ort_sys.rs" -- -x c -Wno-pragma-once-outside-header
rustfmt --edition 2021 "$TMP/ort_sys.rs"
minor="$(echo "$ORT_VERSION" | cut -d. -f2)"
{
	echo "//! ONNX Runtime 1.$minor C API, generated by bindgen $(bindgen --version | awk '{print $2}') from onnxruntime_c_api.h. Do not edit."
	echo "//! The oldest API the plugin EP can be loaded by; see lib.rs. Regenerate with guest/ane-ep/bindgen.sh."
	echo "#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code, unsafe_op_in_unsafe_fn)]"
	cat "$TMP/ort_sys.rs"
} > "$HERE/src/ort_sys.rs"
grep -q "pub const ORT_API_VERSION: u32 = $minor;" "$HERE/src/ort_sys.rs"
echo "src/ort_sys.rs: ONNX Runtime $ORT_VERSION, API $minor"
